### ISSUE TITLE
[Upstream dependency] Caching proxy support

### ISSUE THREAD

**Issue by webframp** [fnichol/dvm#1]
It would be great to work polipo support into the mix

**Comment by fnichol** [comment]
I've been looking into this and we might have an upstream issue now. From my reading, as of https://github.com/dotcloud/docker/commit/fcee6056dc50de7698772a3049cdfa1eb0f2416f the registry calls (to download images) will attempt HTTPS first and then fallback to HTTP.

Additionally, Docker is using Go's net/http (using [transport](http://golang.org/src/pkg/net/http/transport.go) under the covers) which I'm having a hard time confirming whether or not `HTTPS_PROXY` will be honored.

We will very likely need to submit and issue/pull request against Docker to fix this which could be considered a regression on proxy support.

**Comment by fnichol** [comment]
Going to close this until we have an upstream option. Until then, the dream is alive!
