### ISSUE TITLE
BootToDocker 0.5.2

### ISSUE THREAD

**Issue by drewcrawford** [fnichol/dvm#15]
Please update to Boot2Docker 0.5.2 or later

**Comment by mainyaa** [comment]
:+1: 
We need Boot2Docker 0.5.2 (Docker 0.8)

**Comment by joelmoss** [comment]
:+1:

**Comment by fnichol** [comment]
Currently dvm is using the Vagrant base box from https://github.com/mitchellh/boot2docker-vagrant-box. If we can get a new [release](https://github.com/mitchellh/boot2docker-vagrant-box/releases) there, it shouldn't be too hard to cut an update

**Comment by drewcrawford** [comment]
I submitted a [PR](https://github.com/mitchellh/boot2docker-vagrant-box/pull/17) to the upstream project.  

Their patch queue seems a little full, so I made a [build](https://www.dropbox.com/s/vy38waom6fvg3p4/boot2docker.box) with my patch applied.  Depending on how much you trust me, that could be at least an interim solution.

**Comment by drewcrawford** [comment]
If anyone wants an unofficial workaround, [this commit](https://github.com/drewcrawford/dvm/commit/e85110093f9820e61d4a753a03bdfbc90f5ab159) upgrades dvm to boot2docker 0.5.4 / docker 0.8.

I'm not submitting a PR here since there is still discussion upstream about which way they want to go and although my approach landed in the upstream patch queue first, they may want to solve it another way and I think it will take them some time to decide.  So until and unless that happens my solution is unofficial.  That said, it does work as far as dvm is concerned, which is good enough for me.

**Comment by fnichol** [comment]
Looks like we should get an upstream release of the base box shortly and I will follow up with a new dvm release. I need it as well :smile:

**Comment by fnichol** [comment]
With the 0.4.0 and 0.4.1 releases we're on boot2docker 0.5.4, yay!
