### ISSUE TITLE
installed via brew tap, dvm up errors:  'Linux_64' is not a valid Guest OS type

### ISSUE THREAD

**Issue by drnic** [fnichol/dvm#16]
```
$ dvm -v
dvm: 0.3.0
$ VBoxManage -v     
4.2.12r84980
$ vagrant -v
Vagrant 1.4.2

$ dvm up
Bringing machine 'dvm' up with 'virtualbox' provider...
[dvm] Importing base box 'boot2docker-0.4.0'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/Users/drnic/.vagrant.d/boxes/boot2docker-0.4.0/virtualbox/box.ovf"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/drnic/.vagrant.d/boxes/boot2docker-0.4.0/virtualbox/box.ovf...
VBoxManage: error: 'Linux_64' is not a valid Guest OS type
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component VirtualBox, interface IVirtualBox, callee IAppliance
VBoxManage: error: Context: "Interpret" at line 330 of file VBoxManageAppliance.cpp
```

**Comment by webdev** [comment]
same here

**Comment by webdev** [comment]
@drnic I upgraded VirtualBox, and it fixed the issue

**Comment by fnichol** [comment]
@drnic What version of VirtualBox are you using (`VBoxManage -version`)? I know this has been [reported](https://github.com/mitchellh/boot2docker-vagrant-box/issues/11) in the [upstream](https://github.com/mitchellh/boot2docker-vagrant-box) base box project.

**Comment by drnic** [comment]
I've upgraded VB and the problem has gone away, thanks!

**Comment by fnichol** [comment]
Yes! Also, should able to support boot2docker 0.5.4 as soon as a fresh Vagrant base box is cut.

**Comment by drnic** [comment]
Are you casting blame and/or saying there's nothing you can do?

**Comment by fnichol** [comment]
Well, I could build my own base box for this, but Mitchell's a pretty awesome person :)

**Comment by fnichol** [comment]
Just added that as a note as Mitchell's getting another release cut shortly, yippie!

**Comment by drnic** [comment]
:)
