### ISSUE TITLE
dvm up Error: Connection timeout. Retrying...

### ISSUE THREAD

**Issue by medcl** [fnichol/dvm#25]
localhost:bin medcl$ dvm up
Bringing machine 'dvm' up with 'virtualbox' provider...
==> dvm: Importing base box 'boot2docker-0.5.4-1'...
==> dvm: Matching MAC address for NAT networking...
==> dvm: Setting the name of the VM: dvm_dvm_1395208518522_99598
==> dvm: Clearing any previously set network interfaces...
==> dvm: Preparing network interfaces based on configuration...
    dvm: Adapter 1: nat
    dvm: Adapter 2: hostonly
==> dvm: Forwarding ports...
    dvm: 4243 => 4243 (adapter 1)
    dvm: 22 => 2222 (adapter 1)
==> dvm: Running 'pre-boot' VM customizations...
==> dvm: Booting VM...
==> dvm: Waiting for machine to boot. This may take a few minutes...
    dvm: SSH address: 127.0.0.1:2222
    dvm: SSH username: docker
    dvm: SSH auth method: private key
    dvm: Error: Connection timeout. Retrying...
    dvm: Error: Connection timeout. Retrying...
    dvm: Error: Connection timeout. Retrying...
    dvm: Error: Connection timeout. Retrying...
^C==> dvm: Waiting for cleanup before exiting...
    dvm: Error: Connection timeout. Retrying...
Vagrant exited after cleanup due to external interrupt.

**Comment by fnichol** [comment]
Hi there, would you be able to upgrade to the latest dvm release and see if that resolves your issue? The current dvm release pulls in boot2docker 0.8.0 which has a lot of improvements and differences.

If you find that you're still running into this, could you please reopen? Thank you!
