### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by yacn** [fnichol/dvm#26]
EOM

**Comment by dougireton** [comment]
Just talked with @fnichol today. I'm pretty sure he's going to talk with @mitchellh to get an updated Vagrant box with Docker 0.9.0 installed.

**Comment by yacn** [comment]
That sounds great! Thanks for the update. —
Isaac Boehman

**Comment by dweinstein** [comment]
I've made a release of the `boot2docker` `0.7.1` `vagrant` box [here](https://github.com/dweinstein/boot2docker-vagrant-box/releases/download/v0.7.1/boot2docker_virtualbox.box) which is based on boot2docker [0.7.1](https://github.com/boot2docker/boot2docker/releases/tag/v0.7.1). I also made a [PR](https://github.com/fnichol/dvm/pull/27) for this project (dvm) which also will only work for `vagrant`.

**Comment by fnichol** [comment]
Thankfully it isn't :smile: 

The challenge with this project is depending on two transitive upstream projects, namely [boot2docker-vagrant-box](https://github.com/mitchellh/boot2docker-vagrant-box) and [boot2docker](https://github.com/boot2docker/boot2docker). As such I've been forced to wait on these releases before updating. The good news is that once released, dvm gets all the benefits, yay!
