### ISSUE TITLE
DOCKER_PORT does not seem to alter port of Vagrantfile

### ISSUE THREAD

**Issue by gregburek** [fnichol/dvm#33]
The docker default port unfortunately conflicts with Crashplan on OSX, so I tried to set `DOCKER_PORT` in `~/.dvm/dvm.conf` to something different, but it does not appear to have any effect. 

`lsof -n -i4TCP:4243` on OSX shows `VBoxHeadl` listening and inside of the boot2docker system, `top` shows `/usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:4243` This is after destroying the dvm system to make sure the new `DOCKER_PORT` was picked up. 

Is there a way to do this via `DOCKER_ARGS` that I am missing?

**Comment by fnichol** [comment]
Thank you for reporting, looks like the format of the docker init.d script changed in 0.8.0 of boot2docker.
