### ISSUE TITLE
Support for Parallels?

### ISSUE THREAD

**Issue by wizonesolutions** [fnichol/dvm#34]
https://github.com/Parallels/vagrant-parallels

Cross-reference https://github.com/Parallels/vagrant-parallels/issues/115

**Comment by fnichol** [comment]
Does packer have support for making Parallels base boxes? If so, adding support in https://github.com/mitchellh/boot2docker-vagrant-box would totally be the way to go!

**Comment by wizonesolutions** [comment]
I think someone is working on getting it working with Packer (
https://github.com/rickard-von-essen/packer-parallels), so I'll open an
issue on `boot2docker-vagrant-box`. Thanks!

**Comment by fnichol** [comment]
Great, thanks!
