### ISSUE TITLE
DVM not support VirtualBox 4.3

### ISSUE THREAD

**Issue by bherrup** [fnichol/dvm#39]
VirtualBox's current version is 4.3.  Any chance we can add this to dvm's supported versions?

Thanks!

**Comment by fnichol** [comment]
Hi there, is dvm failing on boot for you? I'm running VirtualBox 4.3.4 on Mac 10.8.5 without any issues (mind you, this is not the very latest release).

**Comment by fnichol** [comment]
Hi @bherrup, in the wake of dvm's 0.6.0 [release](https://github.com/fnichol/dvm/releases/tag/v0.6.0), could I get you to try that release? If you're still having issues, then simply re-open. Thank you!

**Comment by bherrup** [comment]
@fnichol,  I'll test it out tonight!
