### ISSUE TITLE
Support `brew tap fnichol/dvm`

### ISSUE THREAD

**Issue by jfoy** [fnichol/dvm#5]
It would be nice for this install path to work:

``` sh
brew tap fnichol/dvm
brew install dvm
```

This would require moving homebrew/dvm.rb out to the root of its own repo named
fnichol/homebrew-dvm ; see https://github.com/jfoy/homebrew-dvm for an example.

**Comment by fnichol** [comment]
Yeah, love this idea!

**Comment by fnichol** [comment]
Okay, we're set up with [fnichol/hombrew-dvm](https://github.com/fnichol/homebrew-dvm) and all instructions updated. Thank you!
