### ISSUE TITLE
Chasing releases

### ISSUE THREAD

**Issue by miketheman** [fnichol/dvm#50]
Considering that the docker project moves at a speedy pace, how can we keep dvm, boot2docker, docker commandline in sync?

**Comment by kballenegger** [comment]
:+1:

**Comment by gschmutz** [comment]
+1

**Comment by composer22** [comment]
Seriously not working with brew install docker.  The fnichol/boot2docker-vagrant-box is using v1.2.0/boot2docker.iso and the API is not able to communicate to OSX client because they are not release compatible.

**Comment by miketheman** [comment]
I've abandoned use of dvm, in favor of Docker native for Mac. Closing.
